name: tf-plan
on:
  push:

permissions: write-all

jobs:
  plan:
    name: Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
        with:
          token: ${{ secrets.PAT }}
